name: Build and Release APK
on: push
jobs:
  hosting:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - uses: actions/checkout@v3

      # Install Flutter command with a specific version
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'  # Specify a compatible Flutter version
          channel: 'stable'          # Use the stable channel

      # Build Website
      - name: Build Website
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release
        working-directory: ./

      # Deploy Firebase Hosting, only works with 13.7.511
      - name: Deploy Firebase Hosting
        uses: w9jds/firebase-action@v13.7.5
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./
